# Provide relative or absolute path to directory containing .docx files with comments.
# Example: "folder\folder" or "C:\Users\user\Documents"
folder_path = 'tests'

# Specify output xlsx file.
output_file = 'output/comments.xlsx'

# Adds additional response column for convenience. [true/false]
add_columns = false
